name: Java 构建与部署

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 配置 Java 环境
        uses: actions/setup-java@v3
        with:
          java-version: '8' # 选择适当的 Java 版本
          distribution: 'adopt' # 指定所需的发行版，例如 'adopt'、'adopt-hotspot' 等
          token: ${{ secrets.G_TOKEN }}

      - name: 使用 Maven 构建
        run: mvn clean install # 使用 Maven 编译和打包

      - name: 上传 JAR 文件到服务器
        run: |
          ls 
          sshpass -p ${{ secrets.DEPLOY_PASSWORD }} scp -o StrictHostKeyChecking=no -r target/ToolUtil-0.0.1-SNAPSHOT.jar root@182.92.201.19:/opt/

        env:
          #          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} # 存储 GitHub Secrets 中的 SSH 私钥
          #          SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}   # 存储 GitHub Secrets 中的 SSH 公钥
          REMOTE_PASSWORD: ${{ secrets.DEPLOY_PASSWORD }} # 密码

      - name: 运行 Java 应用程序
        run: |
          sshpass -p ${{ secrets.DEPLOY_PASSWORD }} ssh root@182.92.201.19 "sudo fuser -k -n tcp 8086"
          sshpass -p ${{ secrets.DEPLOY_PASSWORD }} ssh root@182.92.201.19 "nohup java -jar /opt/ToolUtil-0.0.1-SNAPSHOT.jar > /dev/null 2>&1 &"